config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/new'
  #get 'sessions/create'
  #get 'sessions/destroy'
  #get 'user/create'
  #get 'user/new'
  #get 'user/index'
  
  
  root 'user#index'
  get '/signup' => 'user#new'
  post '/signup' => 'user#create'
  get '/' => 'user#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

 
  #root 'sessions#new'
  #root 'student#list'
 # resources :student
  get 'students/new'
  post 'students/create'
  patch 'students/update'
  get 'students/list'
  get 'students/show'
  get 'students/edit'
  get 'students/delete'
  get 'students/update'


  







  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

   has_one_attached :profile_image
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # protect_from_forgery with: :exception
    protect_from_forgery with: :null_session

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  
  end

  def create
    user = User.find_by(params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
     # redirect_to root_path, notice:'Logged in successfully'
     redirect_to students_list_path, notice:'Logged in successfully'
    
    else
      flash.now[:alert]="Invalid Email or Password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    
    redirect_to root_path, notice:'logged out successfully'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

        def list
        @students = Student.all
        end
        def show
        @student = Student.find(params[:id])
        end
        def new
        @student = Student.new
        end
        def create
        @student = Student.new(student_params)
        if @student.save
        redirect_to :action => 'list'
        else
        render :action => 'new'
        end
        end
     
        def student_params
        params.require(:student).permit(:first_name, :last_name, :course_name, :grade, :profile_image)
        end

        
        def edit
        @student = Student.find(params[:id])
        end
        def student_param
        params.require(:student).permit(:first_name, :last_name, :course_name, :grade, :profile_image)
        end
        def update
        @student = Student.find(params[:id])
        if @student.update(student_param)
        redirect_to :action => 'show', :id => @student
        else
        render :action => 'edit'
        end
        end
        def delete
        Student.find(params[:id]).destroy
        redirect_to :action => 'list'
        end
        end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user_id
    redirect_to root_path, notice:"Your account is successfully created"
    else
    render :new    
    end
  end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def new
    @user=User.new
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <title>Aleem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>
  <body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='container'>
      <%= yield %>
      </div>
    </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student Detail</h1>

<%= simple_form_for @student, :url =>{:action => "update", :id =>@student} do |f| %>

    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :course_name %>
    <%= f.input :grade %>
    <%= f.file_field :profile_image %><br><br>
    <%= f.button :submit %>
<% end %>

<%= link_to 'Back', {:action => 'list' } %>

app/views/students/list.html.erb
<!DOCTYPE html>
<html>
<body>
<% if @students.blank? %>
<p>There are not any students currently in the system.</p>
<% else %>
<p>These are the students list</p>
<ul id = "students">
<% @students.each do |c| %>
<li>
<%= link_to c.first_name, {:action => 'show', :id => c.id} -%>
<b> <%= link_to 'Edit', {:action => 'edit', :id => c.id} %></b>
<b> <%= link_to "Delete", {:action => 'delete', :id => c.id},
:confirm => "Are you sure you want to delete this item?" %></b>
</li>
<% end %>
</ul>

<% end %>
<p><%= link_to "Add new Student", students_new_path %></p>
<%= button_to 'Logout', logout_path, method: :destroy %>
</body>

</html>

app/views/students/new.html.erb
<h1>Add new student</h1>

<%= simple_form_for @student, :url => { :action => "create" } do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :course_name %>
    <%= f.input :grade %>
    <%= f.file_field :profile_image %><br><br>
    <%= f.button :submit %>

<% end %>
<%= link_to 'Back', {:action => 'list'} %>

app/views/students/show.html.erb
<%= image_tag @student.profile_image  if  @student.profile_image.attached? %>
<h1><%= @student.first_name + @student.last_name %></h1>
<p>
<strong>Course: </strong> <%= @student.course_name %><br />
<strong>Grade: </strong> <%= @student.grade %><br />
<strong>Created Date:</strong> <%= @student.created_at %><br />
</p>


<%= link_to 'Back', {:action => 'list'} %>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/index.html.erb
<h1>welcome to main page</h1>

<%= link_to 'Sign Up', signup_path %>
    or
    <%= link_to 'Log In', login_path %>
  

app/views/user/new.html.erb
<%= simple_form_for :user, url: '/signup' do |f| %>
    <h1>Sign Up</h1>
    <%= f.input :first_name %><br>
    <%= f.input :last_name %><br>
    <%= f.input :email %><br>
    <%= f.input :password %><br>
    <%= f.button :submit %>
    <%= link_to 'Already have an account!Log In', login_path %>
 
    <% end %>

    
    
    
    
    
    
    
    
    
    
    